branch-defaults:
  main:
    environment: hello-springrest-1
global:
  application_name: hello-springrest
  branch: null
  default_ec2_keyname: clave-lucatic2
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
